### ISSUE TITLE
How to navigate to folder within workspace quickly?

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#144]
How can I quickly navigate to a folder (that I use very often) in Nota?
Right now, I need to navigate manually by searching it in the file tree.

- There's no "Go to folder…" command in the palette
- I could not figure out how to write a custom command either

Problems with custom command:

```
#!/bin/bash
# @parameters workspace
nota $1/folder_name
```

This will open the folder as root in a new workspace and not navigate to the folder.

**Comment by astoilkov** [comment]
We actually have the same problem. I currently use ⌘⇧E to focus the sidebar, hit Left to focus the FolderBar, and then start typing. However, this workflow is frustrating so we want to create exactly what you are proposing "Go to Folder..." dialog.

Hope this lands soon.

One quick question: You want to go to the folder in order to explore its contents right? Not for creating a note there?

**Comment by minthemiddle** [comment]
Yes, to explore content. It's a Zettelkasten folder with long file names such as `211023232039` that don't disclose information about the content. So I can't memorize a file in the folder and just go to this file.

**Comment by astoilkov** [comment]
Cool. Thanks.

We will probably implement this soon.

**Comment by astoilkov** [comment]
### 🎉🎉🎉

We've implemented a Go to Folder... dialog. The next minor release will include the feature.

**Comment by astoilkov** [comment]
Now part of the 0.35 release. Closing this. Once again, thanks!
