### ISSUE TITLE
Custom "Paste" keyboard shortcut doesn't work 

### ISSUE THREAD

**Issue by borekb** [notaapp/talk#155]
I reconfigured Cmd-V to do "Paste Clean" which I personally prefer most of the time but occasionally, "Paste" (rich) would also be useful.

I tried setting up two keyboard shortcuts for it, `Cmd-Shift-V` and `Ctrl-Shift-V`, neither of them works, unfortunately (nothing happens when I press it).

<img width="374" alt="Screen Shot 2022-02-09 at 16 44 37" src="https://user-images.githubusercontent.com/101152/153236424-ae15e1d6-46aa-43cd-ae54-231d154c6b4f.png">

The only way to paste with formatting is to right-click on the canvas and select "Paste":

<img width="195" alt="Screen Shot 2022-02-09 at 16 45 34" src="https://user-images.githubusercontent.com/101152/153236572-67211458-a579-4078-b5b8-92c1d99a9d28.png">

(The keyboard shortcut hint in this menu is wrong, I guess it doesn't reflect the Preferences / Shortcuts properly.)

_I think I already reported this somewhere but can't find it; maybe it was private conversation so I'm rather creating an issue for it._

**Comment by astoilkov** [comment]
Yes, you have previously reported this in a private conversation. I've also tried to fix it but it's harder than I thought initially (because of some Electron specifics when handling native commands like "paste").

We are currently working on improving the paste experience and with it, we will also fix this issue. However, it may take a little more time than a regular bug fix should take.

**Comment by astoilkov** [comment]
In 0.35 you can swap the shortcuts and it will work. Closing this issue. Sorry for the delay Borek!
