### ISSUE TITLE
Feature Request: Sync keyboard shortcuts between machines

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#202]
Right now (Nota v0.35.3), I have to set up the keyboard shortcuts afresh on every machines. The setting does not seem to sync via `.nota` folder.

It would be very helpful to sync the keyboard shortcuts also between machines.

Side notes:
Are shortcuts tied to one workspace or global? I have workspace specific shortcuts (i.e. link to one specific file within the workspace), so they would not work in a different workspace, but I only have one. I guess the scope of keyboard shortcuts is the challenge here…

**Comment by astoilkov** [comment]
That's a duplicate — https://github.com/notaapp/talk/issues/135. We are already thinking about this. We should do something about this.

> Are shortcuts tied to one workspace or global?

Global. However, if you have a shortcut to a custom command the shortcut won't be applied in a different workspace because the command doesn't exist there.

Closing this. We can continue the conversation in the original issue.
