### ISSUE TITLE
v0.40.3 randomly switching tabs

### ISSUE THREAD

**Issue by jakemingolla** [notaapp/talk#383]
I recently updated to the latest version and I can no longer use the application without randomly being changed to a different note every time I click into the main window. The left navigation bar is completely unusable and responds to maybe 1/2 the selections I make - other times it just puts the left navigation bar out of view and undoes any selection I made to change notes. I can't rely provide any screenshots as the note permanently stuck in the view contains personal information - happy to describe it more in depth if that is helpful.

```
Nota Version 0.40.3 (Apple Silicon)
Mac OS 13.2.1 (22D68)
```

**Comment by astoilkov** [comment]
Wow, this is serious.

Can you switch your workspace (⌃R) and open another one? Does the problem persist there? If yes, can you record a video from a workspace that doesn't contain any personal information?

I'm asking for a video because describing such bizarre problems is hard. Even my co-founder (with whom we share similar vocabulary) has problems describing those.

Thanks in advance!

**Comment by astoilkov** [comment]
I fixed the issue and published a new release containing the fix.

The problem is that you have too many tabs open. The new release allows for a maximum of 20 tabs — older tabs get closed.

Thanks for taking the time to report this!
